id: P008133
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN4645
  title: སྐྱེ་བ་སྔ་ཕྱིའི་རྣམ་གཞག་དང་ལུགས་གཉིས་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    7e9b36eb9a2c4dc3958d80719705bb9c:
      image_group_id: I3CN4647
      title: Volume 1 of skye ba snga phyi'i rnam gzhag dang lugs gnyis gsal ba'i
        me long /
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
