id: P008133
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4645
  title: སྐྱེ་བ་སྔ་ཕྱིའི་རྣམ་གཞག་དང་ལུགས་གཉིས་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    d4a70c4014ce48dfa3c5da7a0a445e5b:
      image_group_id: I3CN4647
      title: ''
      volume_number: 1
      total_pages: 416
ebook_metadata:
  title: སྐྱེ་བ་སྔ་ཕྱིའི་རྣམ་གཞག་དང་ལུགས་གཉིས་གསལ་བའི་མེ་ལོང་།
  author: ''
  sku: P008133
  cover: cover.jpg
  layers:
  - pagination
